export const ROUTES = {
  LOGIN: "/login",
  REGISTER: "/register",
  ROOT: "/",
  DASHBOARD: "/dashboard",
  PRODUCTS: "/products",
  PRODUCT_DETAIL: "/products/:id",
  FAVORITES: "/favorites",
  INBOX: "/inbox",
  ORDERS: "/orders",
  PRODUCT_STOCK: "/product-stock",
  PRICING: "/pricing",
  CALENDAR: "/calendar",
  TODO: "/todo",
  CONTACT: "/contact",
  ADD_CONTACT: "/contact/add",
  CONTACT_DETAIL: "/contact/:id",
  INVOICE: "/invoice",
  UI_ELEMENTS: "/ui-elements",
  TEAM: "/team",
  ADD_TEAM: "/team/add",
  TEAM_DETAIL: "/team/:id",
  TABLE: "/table",
  SETTINGS: "/settings",
} as const;
