export const ROUTES = {
  LOGIN: "/login",
  ROOT: "/",
  DASHBOARD: "/dashboard",
  PRODUCTS: "/products",
  FAVORITES: "/favorites",
  INBOX: "/inbox",
  ORDERS: "/orders",
  PRODUCT_STOCK: "/product-stock",
  PRICING: "/pricing",
  CALENDAR: "/calendar",
  TODO: "/todo",
  CONTACT: "/contact",
  ADD_CONTACT: "/contact/add",
  INVOICE: "/invoice",
  UI_ELEMENT: "/ui-element",
  TEAM: "/team",
  ADD_TEAM: "/team/add",
  TABLE: "/table",
  SETTINGS: "/settings",
} as const;
